var p=Object.defineProperty;var k=Object.getOwnPropertyDescriptor;var x=Object.getOwnPropertyNames;var L=Object.prototype.hasOwnProperty;var O=(n,e)=>{for(var t in e)p(n,t,{get:e[t],enumerable:!0})},T=(n,e,t,s)=>{if(e&&typeof e=="object"||typeof e=="function")for(let i of x(e))!L.call(n,i)&&i!==t&&p(n,i,{get:()=>e[i],enumerable:!(s=k(e,i))||s.enumerable});return n};var b=n=>T(p({},"__esModule",{value:!0}),n);var N={};O(N,{default:()=>h});module.exports=b(N);var a=require("obsidian"),l=require("@codemirror/view"),v=require("@codemirror/state"),d={showUrls:!0,showLinks:!0,statsColor:"#999999",lineColor:"#999999",eofColor:"#999999"};function E(n){let e=n.replace(/^---[\s\S]*?---\n?/,""),t=/https?:\/\/[^\s\)\]>]+/g,s=new Set(e.match(t)||[]),i=/\[\[([^\]|#]+)/g,o=new Set,r;for(;(r=i.exec(e))!==null;)o.add(r[1]);return{urls:s.size,links:o.size}}function w(n){return n.toLocaleString()}function F(n,e){let t=[];return e.showUrls&&t.push(`URLs: ${w(n.urls)}`),e.showLinks&&t.push(`Links: ${w(n.links)}`),t.join(" | ")}var S=class extends l.WidgetType{constructor(t,s){super();this.stats=t;this.settings=s}toDOM(){let t=document.createElement("div");t.className="eof-stats-container";let s=F(this.stats,this.settings);if(s){let o=document.createElement("div");o.className="eof-stats-line",o.textContent=s,o.style.color=this.settings.statsColor,t.appendChild(o)}let i=document.createElement("div");return i.className="eof-indicator",i.innerHTML=`
      <div class="eof-line-horizontal" style="border-color: ${this.settings.lineColor}"></div>
      <div class="eof-text" style="color: ${this.settings.eofColor}">EOF</div>
      <div class="eof-line-horizontal" style="border-color: ${this.settings.lineColor}"></div>
    `,t.appendChild(i),t}eq(t){return this.stats.urls===t.stats.urls&&this.stats.links===t.stats.links&&this.settings.showUrls===t.settings.showUrls&&this.settings.showLinks===t.settings.showLinks&&this.settings.statsColor===t.settings.statsColor&&this.settings.lineColor===t.settings.lineColor&&this.settings.eofColor===t.settings.eofColor}};function m(n,e){let t=E(n),s=new S(t,e),i=l.Decoration.widget({widget:s,side:1,block:!0});return l.Decoration.set([i.range(n.length)])}function P(n){return v.StateField.define({create(e){return m(e.doc.toString(),n.settings)},update(e,t){return t.docChanged?m(t.state.doc.toString(),n.settings):e.map(t.changes)},provide:e=>l.EditorView.decorations.from(e)})}var f=class extends a.PluginSettingTab{constructor(t,s){super(t,s);this.plugin=s}display(){let{containerEl:t}=this;t.empty(),t.createEl("h2",{text:"EOF Stats Settings"}),t.createEl("h3",{text:"Display Items"}),new a.Setting(t).setName("Show URLs").setDesc("Display the count of unique URLs").addToggle(s=>s.setValue(this.plugin.settings.showUrls).onChange(async i=>{this.plugin.settings.showUrls=i,await this.plugin.saveSettings()})),new a.Setting(t).setName("Show Links").setDesc("Display the count of unique internal links").addToggle(s=>s.setValue(this.plugin.settings.showLinks).onChange(async i=>{this.plugin.settings.showLinks=i,await this.plugin.saveSettings()})),t.createEl("h3",{text:"Colors"}),new a.Setting(t).setName("Stats Color").setDesc("Color for the statistics text").addText(s=>s.setPlaceholder("#999999").setValue(this.plugin.settings.statsColor).onChange(async i=>{this.plugin.settings.statsColor=i||d.statsColor,await this.plugin.saveSettings()})),new a.Setting(t).setName("Line Color").setDesc("Color for the horizontal lines").addText(s=>s.setPlaceholder("#999999").setValue(this.plugin.settings.lineColor).onChange(async i=>{this.plugin.settings.lineColor=i||d.lineColor,await this.plugin.saveSettings()})),new a.Setting(t).setName("EOF Color").setDesc("Color for the EOF text").addText(s=>s.setPlaceholder("#999999").setValue(this.plugin.settings.eofColor).onChange(async i=>{this.plugin.settings.eofColor=i||d.eofColor,await this.plugin.saveSettings()}))}},h=class extends a.Plugin{async onload(){await this.loadSettings(),this.addSettingTab(new f(this.app,this)),this.registerEditorExtension(P(this)),this.registerMarkdownPostProcessor((t,s)=>{this.addEOFToReadingView(t,s)})}onunload(){}async loadSettings(){this.settings=Object.assign({},d,await this.loadData())}async saveSettings(){await this.saveData(this.settings),this.app.workspace.updateOptions()}addEOFToReadingView(t,s){let i=s.getSectionInfo(t);if(!i)return;let o=this.app.vault.getAbstractFileByPath(s.sourcePath);o&&this.app.vault.cachedRead(o).then(r=>{let y=r.split(`
`).length-1;if(i.lineEnd>=y){let D=E(r),c=document.createElement("div");c.className="eof-stats-container";let C=F(D,this.settings);if(C){let g=document.createElement("div");g.className="eof-stats-line",g.textContent=C,g.style.color=this.settings.statsColor,c.appendChild(g)}let u=document.createElement("div");u.className="eof-indicator",u.innerHTML=`
          <div class="eof-line-horizontal" style="border-color: ${this.settings.lineColor}"></div>
          <div class="eof-text" style="color: ${this.settings.eofColor}">EOF</div>
          <div class="eof-line-horizontal" style="border-color: ${this.settings.lineColor}"></div>
        `,c.appendChild(u),t.appendChild(c)}})}};
